name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]


jobs:
  Terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: "1.4.2"
          
    - name: Terraform plan
      id: init
      run: Terraform init
       
    - name: Terraform plan
      id: plan
      run: Terraform plan
       
    - name: Terraform apply
      if: github_event_name == 'push'
      run: terraform apply -auto-approve
      
